version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine3.13
    - 15.12.0.pre.alpine3.13
    - 15.13.0.pre.alpine3.13
    - 15.6.0.pre.alpine3.11
    - 15.7.0.pre.alpine3.11
    - 15.8.0.pre.alpine3.11
    - 15.9.0.pre.alpine3.13
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.4
  - dependency-name: python
    versions:
    - 3.9.2.pre.alpine3.13
