version: 2.1

jobs:
  test:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          apk add --no-cache make python3
          pip3 install --upgrade pipenv

          make test

  push:
    parameters:
      image-name:
        description: Name of the docker image
        type: string
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          apk add --no-cache make

          name="<< parameters.image-name >>"
          make build name=$name

          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push landtech/ci-$name

workflow_jobs: &workflow_jobs
  jobs:
    - test
    - push:
        name: base
        image-name: base
        context: DockerHub
        requires:
          - test

    - push:
        name: node
        image-name: node
        context: DockerHub
        requires:
          - test

    - push:
        name: eb
        image-name: eb
        context: DockerHub
        requires:
          - base

    - push:
        name: kubernetes
        image-name: kubernetes
        context: DockerHub
        requires:
          - node

    - push:
        name: kops
        image-name: kops
        context: DockerHub
        requires:
          - kubernetes

workflows:
  nightly:
    <<: *workflow_jobs
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master

  deploy:
    <<: *workflow_jobs
