version: 2.1

jobs:
  build_and_push:
    parameters:
      image_folder:
        description: Path to image folder
        type: string
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          apk add make

          folder="<< parameters.image_folder >>"
          make test
          make build folder=$folder

          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push landtech/ci-$folder

workflow_jobs: &workflow_jobs
  jobs:
    - build_and_push:
        name: build_base
        image_folder: base
        context: DockerHub

    - build_and_push:
        name: build_node
        image_folder: node
        context: DockerHub

    - build_and_push:
        name: build_eb
        image_folder: eb
        context: DockerHub
        requires:
          - build_base

    - build_and_push:
        name: build_kubernetes
        image_folder: kubernetes
        context: DockerHub
        requires:
          - build_node

    - build_and_push:
        name: build_kops
        image_folder: kops
        context: DockerHub
        requires:
          - build_kubernetes

workflows:
  nightly:
    <<: *workflow_jobs
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master

  deploy:
    <<: *workflow_jobs
