version: 2.1

executors:
  default:
    docker:
      - image: alpine:latest

commands:
  prerequisites:
    steps:
      - run: |
          apk add --no-cache \
            bats \
            coreutils \
            curl \
            docker \
            grep \
            jq \
            make \
            python3 \
            py3-pip
          pip3 install --upgrade pipenv
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

jobs:
  shared_tests:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - prerequisites
      - run: make test_semver

  base:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - prerequisites
      - run: |
          make base

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker tag landtech/ci-base landtech/ci-base:$CIRCLE_BUILD_NUM
            docker push landtech/ci-base
            docker push landtech/ci-base:$CIRCLE_BUILD_NUM
          fi

  kops:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - prerequisites
      - run: |
          make kops

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            version="$(jq -r .kops version.json)"
            docker tag landtech/ci-kops landtech/ci-kops:$version
            docker push landtech/ci-kops
            docker push landtech/ci-kops:$version
          fi

  node:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - prerequisites
      - run: ./Dockerfile_node.sh "$CIRCLE_BRANCH"

  kubernetes:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - prerequisites
      - run: |
          make kubernetes

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker push landtech/ci-kubernetes
          fi

  eb:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - prerequisites
      - run: |
          version="$(curl -s --retry 5 --retry-delay 5 https://pypi.org/pypi/awsebcli/json | jq -r '.releases | keys[]' | sort --version-sort | tail -n 1)"
          make eb version=$version

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker tag landtech/ci-eb landtech/ci-eb:$version
            docker push landtech/ci-eb
            docker push landtech/ci-eb:$version
          fi

workflow_jobs: &workflow_jobs
  jobs:
    - shared_tests:
        context: DockerHub

    - base:
        context: DockerHub
        requires:
          - shared_tests

    - node:
        context: DockerHub
        requires:
          - shared_tests

    - kubernetes:
        context: DockerHub
        requires:
          - shared_tests

    - kops:
        context: DockerHub
        requires:
          - shared_tests

workflows:
  weekly:
    <<: *workflow_jobs
    triggers:
      - schedule:
          cron: "0 8 * * 1"
          filters:
            branches:
              only: master

  deploy:
    <<: *workflow_jobs
