version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t landtech/ci-base .
            docker login --username landtech --password $DOCKER_PASSWORD
            docker push landtech/ci-base

workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 5 * * 1"
          filters:
            branches:
              only: master
