version: 2.1

executors:
  default:
    docker:
      - image: docker:stable

commands:
  prerequisites:
    steps:
      - run: |
          apk add --no-cache \
            coreutils \
            curl \
            grep \
            jq \
            make \
            python3
          pip3 install --upgrade pip pipenv
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

jobs:
  shared_tests:
    executor: default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: |
          apk add --no-cache \
            bats
          ./test.sh

  base:
    executor: default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - prerequisites
      - run: |
          make base

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker tag landtech/ci-base landtech/ci-base:$CIRCLE_BUILD_NUM
            docker push landtech/ci-base
            docker push landtech/ci-base:$CIRCLE_BUILD_NUM
          fi

  kops:
    executor: default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - prerequisites
      - run: |
          version="$(jq -r .kops version.json)"
          make kops version=$version

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker tag landtech/ci-kops landtech/ci-kops:$version
            docker push landtech/ci-kops
            docker push landtech/ci-kops:$version
          fi

  node:
    executor: default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - prerequisites
      - run: |
          make node

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            version=$(cat Dockerfile_node| head -n 1 | grep -Po "FROM node:\K.+")
            docker tag landtech/ci-node landtech/ci-node:$version
            docker push landtech/ci-node
            docker push landtech/ci-node:$version
          fi

  kubernetes:
    executor: default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - prerequisites
      - run: |
          make kubernetes

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker push landtech/ci-kubernetes
          fi

  eb:
    executor: default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - prerequisites
      - run: |
          version="$(curl -s --retry 5 --retry-delay 5 https://pypi.org/pypi/awsebcli/json | jq -r '.releases | keys[]' | sort --version-sort | tail -n 1)"
          make eb version=$version

          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker tag landtech/ci-eb landtech/ci-eb:$version
            docker push landtech/ci-eb
            docker push landtech/ci-eb:$version
          fi

workflow_jobs: &workflow_jobs
  jobs:
    - shared_tests:
        context: DockerHub

    - base:
        context: DockerHub
        requires:
          - shared_tests

    - node:
        context: DockerHub
        requires:
          - shared_tests

    - eb:
        context: DockerHub
        requires:
          - base

    - kubernetes:
        context: DockerHub
        requires:
          - node

    - kops:
        context: DockerHub
        requires:
          - kubernetes

workflows:
  nightly:
    <<: *workflow_jobs
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master

  deploy:
    <<: *workflow_jobs
